# stack.yaml docs:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
resolver: lts-9.0

packages:
- .

extra-deps: []

flags: {}

extra-package-dbs: []
