eg/negation: \
  eg/negation.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
eg/negation.o: \
  eg/negation.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
eg/sorting: \
  eg/sorting.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
eg/sorting.o: \
  eg/sorting.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
src/FitSpec/Derive.o: \
  src/FitSpec/Derive.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs
src/FitSpec/Dot.o: \
  src/FitSpec/Dot.hs \
  src/FitSpec.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Utils.hs \
  src/FitSpec/TestTypes.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/ShowMutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs
src/FitSpec/Engine.o: \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  src/FitSpec/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/Engine: \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  src/FitSpec/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/Main.o: \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/Utils.hs
src/FitSpec/Main: \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/Utils.hs
src/FitSpec/Most.o: \
  src/FitSpec/Most.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
src/FitSpec/Mutable.o: \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/Mutable/Tuples.o: \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec.o: \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
src/FitSpec/PrettyPrint.o: \
  src/FitSpec/PrettyPrint.hs
src/FitSpec/Report.o: \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Utils.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/Report: \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Utils.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/ShowMutable.o: \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec/ShowMutable/Tuples.o: \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
src/FitSpec: \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
src/FitSpec/TestTypes.o: \
  src/FitSpec/TestTypes.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  src/FitSpec/Mutable.hs \
  src/FitSpec/ShowMutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs
src/FitSpec/Utils.o: \
  src/FitSpec/Utils.hs
tests/test-derive.o: \
  tests/test-derive.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
tests/test-derive: \
  tests/test-derive.hs \
  src/FitSpec.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Utils.hs
tests/test-mutate.o: \
  tests/test-mutate.hs \
  src/FitSpec.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Utils.hs \
  src/FitSpec/TestTypes.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Function/ListsOfPairs.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/ShowMutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs
tests/test-mutate: \
  tests/test-mutate.hs \
  src/FitSpec.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Utils.hs \
  src/FitSpec/TestTypes.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Function/ListsOfPairs.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/ShowMutable.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/PrettyPrint.hs
tests/test-showmutable.o: \
  tests/test-showmutable.hs \
  src/FitSpec.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/Utils.hs
tests/test-showmutable: \
  tests/test-showmutable.hs \
  src/FitSpec.hs \
  src/FitSpec/Derive.hs \
  src/FitSpec/ShowMutable/Tuples.hs \
  src/FitSpec/Main.hs \
  src/FitSpec/Report.hs \
  src/FitSpec/TestTypes.hs \
  src/FitSpec/ShowMutable.hs \
  src/FitSpec/PrettyPrint.hs \
  src/FitSpec/Mutable/Tuples.hs \
  src/FitSpec/Engine.hs \
  src/FitSpec/Mutable.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  src/FitSpec/Utils.hs
tests/test-utils.o: \
  tests/test-utils.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  src/FitSpec/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
tests/test-utils: \
  tests/test-utils.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  src/FitSpec/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs
