bench/AVLTree.o: \
  bench/AVLTree.hs
bench/avltrees.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/avltrees.hs \
  bench/AVLTree.hs
bench/avltrees: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/avltrees.hs \
  bench/AVLTree.hs
bench/bools.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/bools.hs
bench/bools: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/bools.hs
bench/Digraph.o: \
  bench/Digraph.hs
bench/digraphs.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/digraphs.hs \
  bench/Digraph.hs
bench/digraphs: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/digraphs.hs \
  bench/Digraph.hs
bench/haskell-src-exts.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/haskell-src-exts.hs
bench/haskell-src-exts: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/haskell-src-exts.hs
bench/haskell-src.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/haskell-src.hs
bench/haskell-src: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/haskell-src.hs
bench/Heap.o: \
  bench/Heap.hs
bench/heaps.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/heaps.hs \
  bench/Heap.hs
bench/heaps: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/heaps.hs \
  bench/Heap.hs
bench/id.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/id.hs
bench/id: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/id.hs
bench/list.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/list.hs
bench/list: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/list.hs
bench/mergeheaps.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/mergeheaps.hs \
  bench/Heap.hs
bench/mergeheaps: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/mergeheaps.hs \
  bench/Heap.hs
bench/pretty.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/pretty.hs
bench/pretty: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/pretty.hs
bench/Set.o: \
  bench/Set.hs
bench/setsofsets.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/setsofsets.hs \
  bench/Set.hs
bench/setsofsets: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/setsofsets.hs \
  bench/Set.hs
bench/sets.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sets.hs \
  bench/Set.hs
bench/sets: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sets.hs \
  bench/Set.hs
bench/sieve.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sieve.hs
bench/sieve: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sieve.hs
bench/sorting.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sorting.hs
bench/sorting: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/sorting.hs
bench/spring.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/spring.hs
bench/spring: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  bench/spring.hs
eg/alga.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/alga.hs
eg/alga: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/alga.hs
eg/negation.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/negation.hs
eg/negation: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/negation.hs
eg/sorting.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/sorting.hs
eg/sorting: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs \
  eg/sorting.hs
src/Test/FitSpec/Derive.o: \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Derive.hs
src/Test/FitSpec/Dot.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Dot.hs \
  src/Test/FitSpec/Derive.hs
src/Test/FitSpec/Engine.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/Engine: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/Main.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/Main: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/Mutable.o: \
  src/Test/FitSpec/Mutable.hs
src/Test/FitSpec/Mutable/Tuples.o: \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs
src/Test/FitSpec.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
src/Test/FitSpec/PrettyPrint.o: \
  src/Test/FitSpec/PrettyPrint.hs
src/Test/FitSpec/Report.o: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/Report: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Engine.hs
src/Test/FitSpec/ShowMutable.o: \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/PrettyPrint.hs
src/Test/FitSpec/ShowMutable/Tuples.o: \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/PrettyPrint.hs
src/Test/FitSpec: \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
src/Test/FitSpec/TestTypes.o: \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec/Mutable.hs
src/Test/FitSpec/Utils.o: \
  src/Test/FitSpec/Utils.hs
tests/test-derive.o: \
  tests/test-derive.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-derive: \
  tests/test-derive.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-mutate.o: \
  tests/test-mutate.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-mutate: \
  tests/test-mutate.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-showmutable.o: \
  tests/test-showmutable.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-showmutable: \
  tests/test-showmutable.hs \
  src/Test/FitSpec/Utils.hs \
  src/Test/FitSpec/TestTypes.hs \
  src/Test/FitSpec/ShowMutable/Tuples.hs \
  src/Test/FitSpec/ShowMutable.hs \
  src/Test/FitSpec/Report.hs \
  src/Test/FitSpec/PrettyPrint.hs \
  src/Test/FitSpec.hs \
  src/Test/FitSpec/Mutable/Tuples.hs \
  src/Test/FitSpec/Mutable.hs \
  src/Test/FitSpec/Main.hs \
  src/Test/FitSpec/Engine.hs \
  src/Test/FitSpec/Derive.hs
tests/test-utils.o: \
  tests/test-utils.hs \
  src/Test/FitSpec/Utils.hs
tests/test-utils: \
  tests/test-utils.hs \
  src/Test/FitSpec/Utils.hs
