#!/bin/bash
#
# upload-haddock-to-hackage: script to upload haddock to Hackage
#
# Copyright (c) 2015-2017 Rudy Matela.
# Distributed under the 3-Clause BSD licence.
#
# this must be run from the project root, that contains the .cabal file
errxit() {
	echo "$@"
	exit 1
}
name=`cat *.cabal | grep -iE "(^| )name:"    | sed -e "s/.*: *//;s/ *//"`
ver=`cat  *.cabal | grep -iE "(^| )version:" | sed -e "s/.*: *//;s/ *//"`
[ -n "$name" ] || errxit "error: could not find package name"
[ -n "$ver"  ] || errxit "error: could not find package version"
echo Generating docs for $name-$ver
cabal install --only-dependencies
cabal configure
cabal build
cabal haddock --hyperlink-source --html-location='/package/$pkg/docs' --contents-location='/package/$pkg'
cd dist/doc/html
mv $name $name-$ver-docs
tar -czv --format ustar -f $name-$ver-docs.tar.gz $name-$ver-docs/
echo -n 'user: '; read user
curl \
	-X PUT \
	-H 'Content-Type: application/x-tar' \
	-H 'Content-Encoding: gzip' \
	--data-binary "@$name-$ver-docs.tar.gz" \
	-u "$user" \
	"https://hackage.haskell.org/package/$name-$ver/docs"
